##############################
####### Set Parameters #######
##############################
project_id: tfs
window_size: 200
minimum_word_frequency: 0
cv_fold: 10
emb_norm: l2
remove_punctuation: True
exclude_nonwords: True
detrend_signal: True


###############################
##### Flexible Parameters #####
###############################

# Subject
sid: 625
conv_ids: np.arange(1, 55)
elecs: np.arange(1, 106)
sig_elec_file: 

# sid: 676
# conv_ids: np.arange(1, 79)
# elecs: np.arange(1, 126)
# sig_elec_file: 

# sid: 7170
# conv_ids: np.arange(1, 25)
# elecs: np.arange(1, 256)
# sig_elec_file:

# sid: 798
# conv_ids: np.arange(1, 16)
# elecs: np.arange(1, 199)
# sig_elec_file:


# Embeddings
emb: glove50
context_length: 1
layer_idx: 0


# Embedding modifications: rand, emb, shift
emb_mod: 
pca_to: 50

# Lags
lags: np.arange(-2000,2001,25)
output_dir_name: lag2k-25-all