
# Embeddings
emb: AutoCompressor-Llama-2-7b-6k_from_convo_start

# Embedding modifications: none, rand, emb, shift-emb, concat-emb
emb_mod: shift-emb
# pca_to not used for ridge
pca_to: 0
ridge: True

# Lags
lags: np.arange(-200000,200001,500)
output_dir_name: ridge-lag200k-500-all
