# Embeddings
emb: AutoCompressor-Llama-2-7b-6k_bm25_respect_maxlen

# Embedding modifications: none, rand, emb, shift-emb, concat-emb
emb_mod: shift-emb
# pca_to not used for ridge
pca_to: 0
ridge: True
