# Embeddings
emb: AutoCompressor-Llama-2-7b-6k_baseline_no_retrieval

# Embedding modifications: none, rand, emb, shift-emb, concat-emb
emb_mod: shift-emb
# pca_to not used for ridge
pca_to: 0
ridge: True
