
# Embeddings
emb: AutoCompressor-Llama-2-7b-6k_prev_utterances_30_embeddings

# Embedding modifications: none, rand, emb, shift-emb, concat-emb
emb_mod: shift-emb
# pca_to not used for ridge
pca_to: 0
ridge: True

# Lags
lags: np.arange(-2000,2001,25)

context_length: 64
output_dir_name: ridge-lag2k-25-all
