emb_df_paths: /scratch/gpfs/cc27/results/tfs/798/pickles/embeddings/Meta-Llama-3.1-8B_retrieval_manual_summaryasrawcontext_fixspace_refrecur/full/cnxt_0001/layer_16.pkl
embeds_name: retrieval_fixspace_rr_cl1
