emb_df_paths: /scratch/gpfs/cc27/results/tfs/798/pickles/embeddings/Meta-Llama-3.1-8B_retrieval_manual_summaryasrawcontext_fixspace/full/cnxt_0256/layer_16.pkl
bridge_type: GroupRidgeCV
embeds_name: retrieval_fixspace_cl256_groupcv
