
# Embeddings
emb: gpt2-xl
layer_idx: 24

# Embedding modifications: none, rand, emb, shift-emb, concat-emb
emb_mod: shift-emb

pca_to: 50
ridge: False
himalaya: True

# Lags
lags: np.arange(-2000,2001,25)
