
# Embeddings
emb: gpt2-xl
context_length: 1024
layer_idx: 48 #/48

# Embedding modifications: none, rand, emb, shift-emb, concat-emb
emb_mod: none # shift-emb, concat-emb, rand, arb

pca_to: 50
regularization: none # ridge, lasso or none

# Lags
lags: np.arange(-2000,2001,25)
output_dir_name: lag2k-25-all