# Embeddings
emb: Meta-Llama-3.1-8B-Instruct_retrieval_manual_summaryasrawcontext

# Embedding modifications: none, rand, emb, shift-emb, concat-emb
emb_mod: shift-emb
# pca_to not used for ridge
pca_to: 0
ridge: True
